from lib.constants import KEY


class DEFAULT:
    FIRST_LIQUIDATION = 0.33

    SECOND_LIQUIDATION = 0.5

    STOPLOSS_TRAILING_PROFIT = 0.005

    TRAILING_PROFIT = 0.0025

    STOPLOSS_COEFF = 8

    MAX_ATR = 1

    ONTIME_INTERVAL_SECONDS = 1

    NODATA_TIMEOUT = 15 * KEY.ONE_MINUTE

    QTY_DEVIATION_PLUS = 0 * KEY.PERCENTD
    QTY_DEVIATION_MINUS = 10 * KEY.PERCENTD

    BINANCE_API_LIMIT = 2400
    OKEX_API_LIMIT = 2400
    HUOBI_API_LIMIT = 2400

    LEVERAGE = 5

    MAX_RATIO = 0.6

    MAX_DEQUE = 10